config/routes.rb
Refinery::Application.routes.draw do
  resources :music, :as => :songs, :controller => :songs
  #resources :songs, :as => :music
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :music_settings do
      member do
        match :toggle
      end
    end
    resources :music, :as => :songs, :controller => :songs, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/music_setting.rb
class MusicSetting < ActiveRecord::Base
    
  # colors
  def self.bg
    find_or_create_by_name("bg").color
  end
  def self.leftbg
    find_or_create_by_name("leftbg").color
  end
  def self.lefticon
    find_or_create_by_name("lefticon").color
  end
  def self.voltrack
    find_or_create_by_name("voltrack").color
  end
  def self.volslider
    find_or_create_by_name("volslider").color
  end
  def self.rightbg
    find_or_create_by_name("rightbg").color
  end
  def self.rightbghover
    find_or_create_by_name("rightbghover").color
  end
  def self.righticon
    find_or_create_by_name("righticon").color
  end
  def self.righticonhover
    find_or_create_by_name("righticonhover").color
  end
  def self.loader
    find_or_create_by_name("loader").color
  end
  def self.track
    find_or_create_by_name("track").color
  end
  def self.tracker
    find_or_create_by_name("tracker").color
  end
  def self.border
    find_or_create_by_name("border").color
  end
  def self.skip
    find_or_create_by_name("skip").color
  end
  def self.text
    find_or_create_by_name("text").color
  end  
  # size  
  def self.width
    find_or_create_by_name("width").size.to_s
  end
  # Boolean
  def self.autostart
    find_or_create_by_name("autostart").value 
  end
  def self.loop_track
    find_or_create_by_name("loop_track").value
  end
  def self.animation
    find_or_create_by_name("animation").value
  end
  def self.remaining
    find_or_create_by_name("remaining").value
  end
  def self.noinfo
    find_or_create_by_name("noinfo").value
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  acts_as_indexed :fields => [:title, :description],
                  :index_file => [Rails.root.to_s, "tmp", "index"]
  
  named_scope :published, :conditions => {:published => true}, :order => :position
  
  belongs_to :resource
  
  validates_presence_of :title
  validates_uniqueness_of :title
end

app/controllers/admin/music_settings_controller.rb
module Admin
  class MusicSettingsController < Admin::BaseController
    crudify :music_setting, :title_attribute => :name, :order => "id ASC", :searchable => false

    def toggle
      @music_setting = MusicSetting.find(params[:id])
      @music_setting.toggle!(:value)
      
      flash[:notice] = "Comment from '#{@music_setting.name}' has been set to '#{@music_setting.value ? 'true' : 'false'}'"

      redirect_to :action => 'index'
    end
  end
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < Admin::BaseController

  crudify :song, :title_attribute => :title

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :find_page

  def index
    @songs = Song.published
  end

  def show
    @songs = Song.published # for body_content_right
    @song = Song.find(params[:id], :conditions => {:published => true})
  end

protected

  def find_page
    @page = Page.find_by_link_url("/music")
  end

end

app/helpers/songs_helper.rb
module SongsHelper
  def player(music)
    flashvar = []

    # colors
    flashvar << "bg=#{MusicSetting.bg}" unless MusicSetting.bg == 'E5E5E5'
    flashvar << "leftbg=#{MusicSetting.bg}" unless MusicSetting.leftbg == 'CCCCCC'
    flashvar << "lefticon=#{MusicSetting.lefticon}" unless MusicSetting.lefticon == '333333'
    flashvar << "voltrack=#{MusicSetting.voltrack}" unless MusicSetting.voltrack == 'F2F2F2'
    flashvar << "volslider=#{MusicSetting.volslider}" unless MusicSetting.volslider == '666666'
    flashvar << "rightbg=#{MusicSetting.rightbg}" unless MusicSetting.rightbg == 'B4B4B4'
    flashvar << "rightbghover=#{MusicSetting.rightbghover}" unless MusicSetting.rightbghover == '999999'
    flashvar << "righticon=#{MusicSetting.righticon}" unless MusicSetting.righticon == '333333'
    flashvar << "righticonhover=#{MusicSetting.righticonhover}" unless MusicSetting.righticonhover == 'FFFFFF'
    flashvar << "righticonhover=#{MusicSetting.righticonhover}" unless MusicSetting.righticonhover == 'FFFFFF'
    flashvar << "loader=#{MusicSetting.loader}" unless MusicSetting.loader == '009900'
    flashvar << "track=#{MusicSetting.track}" unless MusicSetting.track == 'FFFFFF'
    flashvar << "tracker=#{MusicSetting.tracker}" unless MusicSetting.tracker == 'DDDDDD'
    flashvar << "border=#{MusicSetting.border}" unless MusicSetting.border == 'CCCCCC'
    flashvar << "skip=#{MusicSetting.skip}" unless MusicSetting.skip == '666666'
    flashvar << "text=#{MusicSetting.text}" unless MusicSetting.text == '333333'
    # Boolean
    flashvar << "autostart=yes" if MusicSetting.autostart == true
    flashvar << "loop=yes" if MusicSetting.loop_track == true
    flashvar << "animation=no" if MusicSetting.animation == false
    flashvar << "remaining=yes" if MusicSetting.remaining == true
    flashvar << "noinfo=yes" if MusicSetting.noinfo == true
    # size
    flashvar << "width=#{MusicSetting.width}"

    if music.respond_to? :each
      artists = []
      titles = []
      files = []
      music.each do |song|
        if song.resource
          artists << song.title
          titles << song.artist
          files << song.resource.url
        end
      end
      flashvar << "titles=#{CGI::escape titles.join(',')}"
      flashvar << "artists=#{CGI::escape artists.join(',')}"
      flashvar << "soundFile=#{CGI::escape files.join(',')}"
    else
      # file info
      flashvar << "titles=#{CGI::escape(music.title)}"
      flashvar << "artists=#{CGI::escape(music.artist)}"
      flashvar << "soundFile=#{CGI::escape(music.resource.url)}"
    end


    raw <<-EOF
    <object type="application/x-shockwave-flash" data="/player.swf" height="84px" width="#{MusicSetting.width}"> 
      <param name="movie" value="/player.swf" /> 
      <param name="FlashVars" value="#{flashvar.join('&')}" /> 
      <param name="quality" value="high" /> 
      <param name="menu" value="true" /> 
      <param name="wmode" value="transparent" /> 
    </object>
    EOF
  end
end

app/views/admin/music_settings/_form.html.erb
<% form_for [:admin,@music_setting] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
        :object => @music_setting,
        :include_object_name => true
      } %>
  <p>
    <strong>
      <%= @music_setting.description -%>
    </strong>
  </p>
  <% if @music_setting.value.nil? && @music_setting.size.nil? %>
    <div class='field'>
      <%= f.label :color -%>
      <div id="colorSelector"><div style="background-color: #<%= @music_setting.color %>"></div></div>
      <%= f.text_field :color -%>
    </div>
  <% elsif @music_setting.value.nil? && @music_setting.color.nil? %>
    <div class='field'>
      <%= f.label :size -%>
      <%= f.text_field :size -%>
    </div>
  <% else %>
    <div class='field'>
      <%= f.label :value -%>
      <%= f.check_box :value -%>
    </div>
  <% end %>

  <%= render :partial => "/shared/admin/form_actions", :locals => {:f => f, :continue_editing => false} %>
<% end -%>

<% content_for :head do %>
  <%= stylesheet_link_tag 'colorpicker' %>
  <%= javascript_include_tag 'colorpicker' %>
  <style>
    #colorSelector {
    	position: relative;
    	width: 36px;
    	height: 36px;
    	background: url(../images/select.png);
    }
    #colorSelector div {
    	position: absolute;
    	top: 3px;
    	left: 3px;
    	width: 30px;
    	height: 30px;
    	background: url(../images/select.png) center;
    }
  </style>
<% end %>

app/views/admin/music_settings/_music_setting.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(music_setting) -%>">
  <span class='title'>
    <span class='actions'>
      <% if music_setting.value != nil  %>
        <%= link_to refinery_icon_tag("#{music_setting.value ? 'cross' : 'tick'}.png"), 
            toggle_admin_music_setting_path(music_setting.id),
            {:title => "Set this setting to #{music_setting.value ? 'false' : 'true'}"} %>
      <% end %>
      <% if music_setting.color %>
        <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_music_setting_path(music_setting),
            :title => 'Edit this color setting' if music_setting.value.nil? %>
      <% end %>

      <% if music_setting.size %>
        <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_music_setting_path(music_setting),
            :title => 'Edit this color setting' if music_setting.value.nil? %>
      <% end %>
            
    </span>
    <strong><%=h music_setting.name %></strong> 
    is set to <strong>
      <%= music_setting.value ? 'true' : 'false' unless music_setting.value.nil? %>
      <%= content_tag('span', "##{music_setting.color}", 
          :style => "background-color:##{music_setting.color};padding:4px" ) unless music_setting.color.nil? %>
      <%= music_setting.size.to_s + 'px' unless music_setting.size.nil? -%>
      </strong> 
    <%= link_to '?', edit_admin_music_setting_path(music_setting), :title => music_setting.description %>
    <span class="preview">&nbsp;</span>
  </span>
</li>

app/views/admin/music_settings/index.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= link_to "Manage Music", admin_songs_url, :class => "back_icon" %>
    </li>
  </ul>
</div>
<div id='records'>
  <% if @music_settings.present? and @music_settings.any? %>
    <%= will_paginate @music_settings, :previous_label => '&laquo;', :next_label => '&raquo;' %>
     <ul id='sortable_list'>
      <%= render :partial => 'music_setting', :collection => @music_settings %>
     </ul>
    <%= will_paginate @music_settings, :previous_label => '&laquo;', :next_label => '&raquo;' %>
  <% end %>
</div>

app/views/admin/songs/_form.html.erb
<%= error_messages_for :song -%>
<% form_for [:admin, @song] do |f| -%>
  
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title -%>
  </div>
  
  <div class='field'>
    <%= f.label :description -%>
    <%= f.text_area :description, :rows => 20, :cols => 140, :class => 'wymeditor' -%>
  </div>
  
  <div class='field'>
    <%= f.label :artist -%>
    <%= f.text_field :artist -%>
  </div>
  
  <div class='field images_field'>
    <%= f.label :resource, 'Audio resource' %>
    <%= render :partial => "/shared/admin/resource_picker", :locals => {:f => f, :field => :resource_id, :resource => @song.resource, :description => "audio resource" } %>
	</div>
  
  <div class='field'>
    <%= f.label :show_download_link -%>
    <%= f.check_box :show_download_link -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions", :locals => {:f => f, :continue_editing => false} %>
<% end -%>

app/views/admin/songs/_song.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(song) -%>">
  <span class='title'>
    <span class='actions'>
      <%= link_to refinery_icon_tag("application_go.png"), song_url(song),
          :title => 'View this song<br/><em>Opens in a new window</em>',
          :target => "_blank" %>
      <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_song_path(song),
           :title => 'Edit this song' %>
      <%= link_to refinery_icon_tag("delete.png"), admin_song_path(song),
          :confirm => 'Are you sure you want to remove this song forever?',
          :class => "cancel", :method => :delete,
          :title => 'Remove this song forever' %>
    </span>
    <%=h song.title %> <span class="preview">&nbsp;</span>
  </span>
</li>

app/views/admin/songs/_songs.html.erb
<%= will_paginate @songs %>
<%= render :partial => "sortable_list" %>

app/views/admin/songs/_sortable_list.html.erb
<%= render :partial => 'song', :collection => @songs %>
<%= render :partial => "/shared/admin/sortable_list" %>

app/views/admin/songs/index.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_songs_url} %>
    </li>
    <li>
      <%= link_to "Create New Music", new_admin_song_url, :class => "add_icon" %>
    </li>
    <li>
      <%= link_to "Edit music settings", admin_music_settings_url, :class => "edit_icon" %>
    </li>
    
  <% if !searching? and Song.count > 1 %>
    <li>
      <%= link_to "Reorder Songs", "", :id => "reorder_action", :class => "reorder_icon" %>
      <%= link_to "Done Reordering Songs", "", :id => "reorder_action_done", :style => "display: none;", :class => "reorder_icon" %>
    </li>
  <% end %>
  </ul>
</div>
<div id='records'>
  <% if searching? %>
    <h2>Search Results for "<%= params[:search] %>"</h2>
    <% if @songs.size > 0 %>
      <%= render :partial => "song", :collection => @songs %>
    <% else %>
      <p>Sorry, no results found.</p>
    <% end %>
  <% else %>
    <% if @songs.size > 0 %>
      <%= will_paginate @songs, :previous_label => '&laquo;', :next_label => '&raquo;' %>
       <ul id='sortable_list'>
        <%= render :partial => "sortable_list" %>
       </ul>
      <%= will_paginate @songs, :previous_label => '&laquo;', :next_label => '&raquo;' %>
    <% else %>
      <p>
        <strong>
          There are no song yet.
          Click "Add a New Song" to add your first song.
        </strong>
      </p>
    <% end %>
  <% end %>
</div>
<%= render :partial => "/shared/admin/make_sortable", :locals => {:tree => false } if !searching? and Song.count > 1 %>

app/views/songs/index.html.erb
<% content_for :body_content_left do %>
  <ul id="songs">
    <% @songs.each do |song| %>
      <li id="track">
        <%= link_to song.title, song_url(song) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/songs/show.html.erb
<% content_for :body_content_title do %>
  <%= @song.artist %> - <%= @song.title %>
<% end %>

<% content_for :body_content_left do %>
  <section>
    <% if @song.resource %>
      <%= player(@song) %>
    <% else %>
      <%= t('.nofile') %>
    <% end %>
    <div class="music-description">
      <%= @song.description.html_safe %>
    </div>
    <% if @song.show_download_link && @song.resource -%>
      <div class="music-download">
        <%= link_to t('.download'), @song.resource.url %><br/>
        <%= t('.download-advice') %>
      </div>
    <% end %>
  </section>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <ul id="track">
      <% @songs.each do |song| -%>
        <li id="track">
          <% if @song == song %>
           <b><%= link_to song.title, song_url(song) %></b>
          <% else %>
            <%= link_to song.title, song_url(song) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </aside>
<% end %>
<%= render :partial => "/shared/content_page" %>